# Generated by Django 4.1.1 on 2022-09-24 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_album_favorites_album_private_photo_favorites'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_url', models.CharField(max_length=150, verbose_name='Ссылка')),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='urls_photo', to='webapp.photo', verbose_name='Фото ссылки')),
            ],
        ),
    ]
